[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "recsys-mlp"
version = "0.1.0"
description = "mlp based latent factor model experiment library (implicit feedback)"
readme = "README.md"
authors = [
    { name = "jayarnim", email = "jayarnim727@email.com" }
]
urls = { Homepage = "https://github.com/jayarnim/pkg-recsys-mlp" }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]